### ISSUE TITLE
edit btn not work

### ISSUE THREAD

**Issue by MautassimAshrafAli** [mguinness/IdentityManagerUI#15]
Edit btn in the first time I make role check it works but when I click in edit btn the second time the edit model does not show.

**Comment by MautassimAshrafAli** [comment]
I fix it 👍 

try {
                                $.each(data.roles, function (index, value) {
                                    cb=document.querySelectorAll("#editForm input[type='checkbox'][value='"+value +"']");for(i in cb){cb[i].checked=true}
                                   
                                });

                            } catch (r) {
                                alert(r);
                            }

**Comment by cthue2** [comment]
> I fix it 👍
> 
> ```js
> try {
>   $.each(data.roles, function (index, value) {
>     cb=document.querySelectorAll("#editForm input[type='checkbox'][value='"+value+"']");
>     for(i in cb) {
>       cb[i].checked=true;
>     }
>   });
> } catch (r) {
>   alert(r);
> }
> ```

Can you post your revised Users.cshtml? I am experiencing the same issue when a role name contains a space.
