### ISSUE TITLE
Edit User modal form will not load when a role contains a space

### ISSUE THREAD

**Issue by cthue2** [mguinness/IdentityManagerUI#17]
If a user is assigned a role containing a space (e.g., "my role"), when you subsequently load the Edit user form for that user, it will not render.

`Uncaught Error: Syntax error, unrecognized expression: #editForm :checkbox[value=my role]`

This appears to originate in the Users.cshtml:

```javascript
$.each(data.roles, function (index, value) {
  //console.log(value);
   $('#editForm :checkbox[value=' + value + ']').prop('checked', true);
});
```

I assume looking for a checkbox with a space in the name raises an exception. Unfortunately, I am not familiar with JavaScript or jQuery to confirm or design a solution.

Thanks!

**Comment by mguinness** [comment]
Try adding quotes around the value.

`$('#editForm :checkbox[value="' + value + '"]').prop('checked', true);`

**Comment by cthue2** [comment]
Thanks, adding the quotes fixed the issue.
