### ISSUE TITLE
Modals don't open

### ISSUE THREAD

**Issue by t1fra** [mguinness/IdentityManagerUI#18]
Hi @mguinness ,

first I want to thank you for this great project! I know you have created the united repo but I have a question for this server side solution.

I've implemented this in my .net 8 solution as I am not using Blazor / Blazor United, just the asp.net core mvc server site project.

When running your core 3.1 solution its working fine. Modal windows do open and I can edit etc.
When running my solution, clicking the buttons like "Edit" on a selected user doesn't open up the Modal. Nothing happens. The Modal TagHelper is recognized but it seems like it is not executing the script code.

Would you have an idea what I am missing?

**Comment by mguinness** [comment]
It could be a bootstrap issue, see issue https://github.com/mguinness/IdentityManagerUI/issues/12 for more info.
