### ISSUE TITLE
Add-Migration generates duplicated foreign keys for Users and Roles related tables

### ISSUE THREAD

**Issue by pgkdev** [mguinness/IdentityManagerUI#2]
Great project!
But when I tested it in a real database using .net core 3.1, the migration was generating duplicated Foreign Keys for Identity respective Users and Roles tables.

The solution was this, maybe you want to fixe it:
`public class ApplicationDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, string> { ... }`
It was missing this part `<ApplicationUser, ApplicationRole, string>` where we specify the customized user and role classes.

Also commented here where the same problem was happening:
[link](https://github.com/dotnet/efcore/issues/9503#issuecomment-708548831)

**Comment by mguinness** [comment]
If you create a PR I'll take a look

**Comment by pgkdev** [comment]
Created the pull request and more information about it.
#3

**Comment by mguinness** [comment]
PR was merged Paulo, thanks for your contribution.
