### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by adrianwright109** [mguinness/IdentityManagerUI#5]
Is this available as a nuget package so I could add it as a package reference?

**Comment by mguinness** [comment]
When packaged you can't [customize the views](https://github.com/dotnet/aspnetcore/issues/27110) or change the models. so decided against creating a NuGet package.

**Comment by JuergenGutsch** [comment]
@mguinness Actually, you can override the views and extend the models. That should work. 
You just need a way to scaffold the views you like to override. 
The same way as Microsoft.AspNetCore.Identity.UI does this by using Microsoft.VisualStudio.Web.CodeGeneration.Design

**Comment by mguinness** [comment]
If you could create a repo demonstrating how this works, I'll take a look.

Outside of Identity UI I've never seen this implemented in another project.

https://github.com/dotnet/Scaffolding/tree/main/src/Scaffolding/VS.Web.CG.Mvc

**Comment by JuergenGutsch** [comment]
Would be a nice side project 👍
