### ISSUE TITLE
Helper for a mix of claim and role checks

### ISSUE THREAD

**Issue by weedkiller** [mguinness/IdentityManagerUI#6]
Hello how can we do a mix of role and claim check as a tagHelper

For e.g in `role==manager && claims=westCoast`

**Comment by mguinness** [comment]
Do you mean something like [Authorize Tag Helper for ASP.NET Core](https://www.davepaquette.com/archive/2017/11/05/authorize-tag-helper.aspx)?

**Comment by weedkiller** [comment]
Ohh yes, seeing the link I can see your Authorize `taghelper` targets both Authorize and Claims! is my understanding correct?
