### ISSUE TITLE
.Net Core 6 & universal

### ISSUE THREAD

**Issue by weedkiller** [mguinness/IdentityManagerUI#7]
Hello https://dotnet.microsoft.com/download/dotnet/6.0 is in preview and getting released soon, since they unified the mobile code base, I am very excited about this lib.

With the unified code base, I am wondering if the same Identity objects would be available in the mobile side as well, would like to be able to use the same admin/IdentityManagerUi even for the mobile devices.

**Comment by mguinness** [comment]
Are you asking if [Microsoft.AspNetCore.Identity](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity) can be used in a Blazor WebAssembly project?

**Comment by weedkiller** [comment]
More so on the mobile apps/IoT side. Previously they had to use [Xaml.Auth](https://www.c-sharpcorner.com/article/oauth-login-authenticating-with-identity-provider-in-xamarin-forms/) now that MS is unifying under the same code base, I thought we could use this codebase on proxying all the authentication mechanisms for mobile and IoT as well. Without any major third party dependencies

![image](https://user-images.githubusercontent.com/21086190/109429635-b4e20c80-79ca-11eb-8d36-d2216e48d986.png)
