### ISSUE TITLE
Cross verify which pages are missing authorization through reflection

### ISSUE THREAD

**Issue by weedkiller** [mguinness/IdentityManagerUI#8]
Hi @mguinness take a peek at [this](https://github.com/mo-esmp/DynamicRoleBasedAuthorizationNETCore), it would be nice during compile or early runtime to run a check and see if any pages are missing or overlapping policies or roles.

The main approach there is to reflect on the assembly, gather the list of the controllers/actions collection and allow user to select which ones to setup.

Our can be to reflect and check which ones we already have, and if any are left missing/open or vulnerable. 

Lastly, Rate limiting or DDOS throttle: https://codeburst.io/rate-limiting-api-endpoints-in-asp-net-core-926e31428017

For the views can we use Bootstrap 5, since its in beta already

**Comment by mguinness** [comment]
While those ideas are good, they're beyond the scope of this project which is to manage the data stored in the following tables.

```
AspNetRoleClaims
AspNetRoles
AspNetUserClaims
AspNetUserRoles
AspNetUsers
```

**Comment by weedkiller** [comment]
gotcha
